### PR TITLE
Links for team.html and minor modifications

### PR DESCRIPTION
**Pull request by adityaray7**
- Added linkedin logo on hover
- create class 'img-box' for images
- change opacity when hovered upon 'img-box'
- added linkedin links for every member
- changed background color of team-container to rgb(150,150,150)

### CODE REVIEW

**Comment by mostlyaman** [comment]
Team page ka color white hi rehne deta

**Comment by mostlyaman** [comment]
Linkedin animations looks good to me.
Just change the background color of the team page and final update the website. Please do this by today if possible.

**Comment by adityaray7** [comment]
Added emails for everyone. Suggest changes or any errors.

**Comment by mostlyaman** [comment]
Google logo ki jagah email ka icon better rahega and make it red on hover instead of blue. I'm sorry for late review, kinda forgot about this. Also, you didn't add the email for FA.


Try to push changes by today.

**Pull request merged**
